### ISSUE TITLE
Food Tracker - Entering invalid food value (not selecting from the drop down but entering it manually) allows the user to save the record

### ISSUE THREAD

**Issue by shanthasprim** [Sprim/DGC-iOS#6]
## Steps To Reproduce:
1. Open the Food Tracker from the left menu.
2. Enter any value for the "Select Food" (not from the drop down) enter other valid values and Click on the 'Save'.
## Actual Result:

some default value is added under the food tracker history
## Expected Result:

Should stay on the same screen and display an error message as "Please select a Valid food item from the dropdown"

**Comment by somepalliprasanthi** [comment]
issue #6 - Fixed.

**Comment by shanthasprim** [comment]
Entering Food value not in the drop down does not close the drop box. Hence user cannot proceed with. Ok to close.
