### ISSUE TITLE
Health Records - Change the Text from "What your want to do?" to "What do you want to do?" on clicking the '+' icon

### ISSUE THREAD

**Issue by shanthasprim** [Sprim/DGC-iOS#7]
## Steps To Reproduce:
1. Open Health Tracker from the left menu.
2. Open any health Parameter. 
3. Click on the '+' icon on the right top corner
## Actual Result:

The alert opens as  "What your want to do?"
## Expected Result:

change the text from "What your want to do?" to "What do you want to do?"

**Comment by somepalliprasanthi** [comment]
issue #7 - Fixed.

**Comment by shanthasprim** [comment]
Working as Expected.
